# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zwa/Documents/C/bp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zwa/Documents/C/bp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zwa/Documents/C/bp/CMakeFiles /Users/zwa/Documents/C/bp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zwa/Documents/C/bp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bp

# Build rule for target.
bp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bp
.PHONY : bp

# fast build rule for target.
bp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/build
.PHONY : bp/fast

csv.o: csv.c.o
.PHONY : csv.o

# target to build an object file
csv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/csv.c.o
.PHONY : csv.c.o

csv.i: csv.c.i
.PHONY : csv.i

# target to preprocess a source file
csv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/csv.c.i
.PHONY : csv.c.i

csv.s: csv.c.s
.PHONY : csv.s

# target to generate assembly for a file
csv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/csv.c.s
.PHONY : csv.c.s

lir.o: lir.c.o
.PHONY : lir.o

# target to build an object file
lir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lir.c.o
.PHONY : lir.c.o

lir.i: lir.c.i
.PHONY : lir.i

# target to preprocess a source file
lir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lir.c.i
.PHONY : lir.c.i

lir.s: lir.c.s
.PHONY : lir.s

# target to generate assembly for a file
lir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lir.c.s
.PHONY : lir.c.s

lirmain.o: lirmain.c.o
.PHONY : lirmain.o

# target to build an object file
lirmain.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lirmain.c.o
.PHONY : lirmain.c.o

lirmain.i: lirmain.c.i
.PHONY : lirmain.i

# target to preprocess a source file
lirmain.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lirmain.c.i
.PHONY : lirmain.c.i

lirmain.s: lirmain.c.s
.PHONY : lirmain.s

# target to generate assembly for a file
lirmain.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bp.dir/build.make CMakeFiles/bp.dir/lirmain.c.s
.PHONY : lirmain.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bp"
	@echo "... csv.o"
	@echo "... csv.i"
	@echo "... csv.s"
	@echo "... lir.o"
	@echo "... lir.i"
	@echo "... lir.s"
	@echo "... lirmain.o"
	@echo "... lirmain.i"
	@echo "... lirmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

